### ISSUE TITLE
SGP won't connect

### ISSUE THREAD

**Issue by kingjamez** [jbrazio/ardufocus#1]
Hi! Thanks for putting this up for us all to use! I've got ardufocus on a Arduino Nano. From the standalone Moonlight focusing software everything works. I can also control it as expected from putty to my COM port. However, SGP won't connect to the device.  When I sniff on the serial port, I see that the Ardufocus is sent :GH# and then it times out with no response. I can send :GH# through putty and I get a response.

**Comment by jbrazio** [comment]
You may need to put the cap to hold the reset line, without it the ASCOM driver will not work.

**Comment by jbrazio** [comment]
Closing after [discussion](https://www.cloudynights.com/topic/585306-ardufocus-open-source-moonlite-compatible-focuser/?p=8125666) on Cloudy Nights forum:

> I added the cap and it's all working perfectly now. I'm using the Moonlight DRO Focuser driver and I have excellent performance on my Moonlight High Res stepper motors. I needed to Mod the steppers in the moonlight unit to be bi-polar instead of unipolar, but they are six wire stepper motors, so I only had to cut one of the six wires and then my DRV8825 controlled the motor perfectly.
