### ISSUE TITLE
Motor wont turn

### ISSUE THREAD

**Issue by Shastarocks** [jbrazio/ardufocus#17]
I have the Nema 17 motor with a A4988 motor controller running off an arduino nano. I cant seem to get the motor to turn. I wired it exactly as [in this diagram](https://stargazerslounge.com/uploads/monthly_2017_07/schematic-bipolar_bb.thumb.jpg.eacc4dea5e85822bc6e35beb76ada258.jpg).

**Comment by jbrazio** [comment]
Hi ! Please try the updated version of the diagram at the [official build instructions](https://ardufocus.com/manual/build-instructions/).
