### ISSUE TITLE
A way to specify step size in UI_KAP

### ISSUE THREAD

**Issue by ccaramel** [jbrazio/ardufocus#19]
Hi,
congratulations for this amazing work!! even I got some issues using Moonlite protocol.

The questions is, I'm currently using UI_KAP function, which is working, but It move step by step at a speed determined by Arduino polling which is very very slow.
Is there a way to interact with this or modify defaults in your code?
Regards.

**Comment by jbrazio** [comment]
Hi ! Do you want to specify a "fixed" speed at build time or have a way to change it on-the-fly when using ? The POT should allow speed changes.

Btw, what sort of issues do you have using the Moonlite protocol ?

**Comment by ccaramel** [comment]
Hi, finally succeeded in setting a fixed value in ui_keybd.cpp then succeded in using a pot to change focus speed. Maybe it could be useful to join a schematic with pot connections. 
The only remaining problem is with acceleration during manual focusing, it would be great to be able to set an acceleration profile dedicated to ui_keybd.

Using MoonLite protocol (both with indi and indigo) it regularly shows an absolute position @0 and a temperature @0 for a few seconds then come back to real value. It has the same behavior using various nanov3 or uno. What do you opine about it?
Regards
