### ISSUE TITLE
Ardufocus is not recognized by the Moolite ASCOM driver

### ISSUE THREAD

**Issue by nikivan1** [jbrazio/ardufocus#24]
Compiled and uploaded the firmware to Arduino Mini. I am able to communicate with it from the Moonlite Single Focuser 
 v1.4 app, but the Moonlite DRO Focuser Driver (downloaded from focuser.com) does not show any devices in the Moonlite Focus Setup menu. I am running the latest version 6.5 of the ASCOM Platform.

**Comment by nikivan1** [comment]
Found about the reset capacitor. With 100nF between Reset and D3 and the appropriate config settings it works.

**Comment by bakosmi** [comment]
please what config settings? i have the same issue and struggle to resolve it. many thanks!

**Comment by jbrazio** [comment]
You need to add a capacitor, otherwise the arduino will reset at every serial connection and the moonlite driver will not recognize the focuser as connected.

> 100nF between Reset and D3

**Comment by bakosmi** [comment]
i have added salvaged led diode between reset and 5v and it works fine - many thanks! :-)
