### ISSUE TITLE
wiring/config.ino

### ISSUE THREAD

**Issue by djibb** [jbrazio/ardufocus#7]
Hi, 

in config.ino, line 104 : 
  #define MOTOR1_PINOUT  12,  11,  10,     8,     7,   6

in schematics : 
https://github.com/jbrazio/ardufocus/blob/master/doc/wiki/schematic-bipolar_bb.png

there's no 6 but 9 pin...

Any hint ?

**Comment by djibb** [comment]
OK. got it. I've wired as explain in INO file. working great -> thanks

**Comment by jbrazio** [comment]
Glad you sorted it out, I'm closing this, reopen if needed.
